name: test
on:
  push:
jobs:
  install:
    runs-on: windows-latest
    strategy:
      matrix:
        R: [ '4.2' ]
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.R }}
      - name: Install devtools
        run: |
          Rscript -e "install.packages('devtools')"
      - name: Setup Dependency
        working-directory: 'tests/setup'
        run: |
          Rscript install_dep_for_tests.R
      - name: Install packages
        run: |
          Rscript -e "install.packages('tidyverse')"
